server:
  port: 8080

spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/LibraryManagementSystem #posgreSQL
    #    url: jdbc:postgresql://host.docker.internal:5432/LibraryManagementSystem #docker
    url: jdbc:postgresql://dpg-d4t669vdiees73asdhsg-a.Singapore-postgres.render.com:5432/librarymanagement_cs88
    username: library_management_db
    #    username: postgres
    #    password: postgres
    password: KqzjgAFHykBUEFWiFXTUSDBSMQd5GrXv
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: production

# JWT Configuration
# 1 hour in milliseconds
jwt:
  secret: ${JWT_SECRET:your-very-strong-secret-key-for-jwt-256-bit-2025-production}
  expiration: ${JWT_EXPIRATION:3600000}

logging:
  level:
    com.system.management.library.aplikasi.book.management: TRACE

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true} # aktif hanya jika SWAGGER_ENABLED=true
    path: /api-docs # ubah jadi /api-docs biar lebih rapi
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html # endpoint UI utama
    url: /api-docs # Swagger langsung ambil /api-docs tanpa isi manual
    display-request-duration: true # opsional, tampilkan waktu respon tiap request
    defaultModelsExpandDepth: -1 # Sembunyikan schemas
    docExpansion: none # Collapse semua sections
    tagsSorter: alpha
    operationsSorter: alpha
